package pojos;
// Generated Jun 8, 2017 11:11:57 PM by Hibernate Tools 4.3.1



/**
 * Chitietxuatsua generated by hbm2java
 */
public class Chitietxuatsua  implements java.io.Serializable {


     private ChitietxuatsuaId id;
     private Double luongsuaxuat;

    public Chitietxuatsua() {
    }

	
    public Chitietxuatsua(ChitietxuatsuaId id) {
        this.id = id;
    }
    public Chitietxuatsua(ChitietxuatsuaId id, Double luongsuaxuat) {
       this.id = id;
       this.luongsuaxuat = luongsuaxuat;
    }
   
    public ChitietxuatsuaId getId() {
        return this.id;
    }
    
    public void setId(ChitietxuatsuaId id) {
        this.id = id;
    }
    public Double getLuongsuaxuat() {
        return this.luongsuaxuat;
    }
    
    public void setLuongsuaxuat(Double luongsuaxuat) {
        this.luongsuaxuat = luongsuaxuat;
    }




}


