package pojos;
// Generated Jun 8, 2017 11:11:57 PM by Hibernate Tools 4.3.1



/**
 * ChitietxuatsuaId generated by hbm2java
 */
public class ChitietxuatsuaId  implements java.io.Serializable {


     private String machungtu;
     private String makho;

    public ChitietxuatsuaId() {
    }

    public ChitietxuatsuaId(String machungtu, String makho) {
       this.machungtu = machungtu;
       this.makho = makho;
    }
   
    public String getMachungtu() {
        return this.machungtu;
    }
    
    public void setMachungtu(String machungtu) {
        this.machungtu = machungtu;
    }
    public String getMakho() {
        return this.makho;
    }
    
    public void setMakho(String makho) {
        this.makho = makho;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitietxuatsuaId) ) return false;
		 ChitietxuatsuaId castOther = ( ChitietxuatsuaId ) other; 
         
		 return ( (this.getMachungtu()==castOther.getMachungtu()) || ( this.getMachungtu()!=null && castOther.getMachungtu()!=null && this.getMachungtu().equals(castOther.getMachungtu()) ) )
 && ( (this.getMakho()==castOther.getMakho()) || ( this.getMakho()!=null && castOther.getMakho()!=null && this.getMakho().equals(castOther.getMakho()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMachungtu() == null ? 0 : this.getMachungtu().hashCode() );
         result = 37 * result + ( getMakho() == null ? 0 : this.getMakho().hashCode() );
         return result;
   }   


}


