package pojos;
// Generated May 30, 2017 10:11:37 PM by Hibernate Tools 4.3.1



/**
 * Counter generated by hbm2java
 */
public class Counter  implements java.io.Serializable {


     private String areaid;
     private Integer indexPhieuxuat;
     private Integer indexPhieunhap;

    public Counter() {
    }

	
    public Counter(String areaid) {
        this.areaid = areaid;
    }
    public Counter(String areaid, Integer indexPhieuxuat, Integer indexPhieunhap) {
       this.areaid = areaid;
       this.indexPhieuxuat = indexPhieuxuat;
       this.indexPhieunhap = indexPhieunhap;
    }
   
    public String getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }
    public Integer getIndexPhieuxuat() {
        return this.indexPhieuxuat;
    }
    
    public void setIndexPhieuxuat(Integer indexPhieuxuat) {
        this.indexPhieuxuat = indexPhieuxuat;
    }
    public Integer getIndexPhieunhap() {
        return this.indexPhieunhap;
    }
    
    public void setIndexPhieunhap(Integer indexPhieunhap) {
        this.indexPhieunhap = indexPhieunhap;
    }




}


