package pojos;
// Generated Jun 8, 2017 11:11:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieunhapbo generated by hbm2java
 */
public class Phieunhapbo  implements java.io.Serializable {


     private String machungtu;
     private Date ngaylap;
     private Date ngaynhap;
     private Integer soluong;
     private Boolean dahuy;
     private String mancc;
     private String manv;
     private String macn;

    public Phieunhapbo() {
    }

	
    public Phieunhapbo(String machungtu) {
        this.machungtu = machungtu;
    }
    public Phieunhapbo(String machungtu, Date ngaylap, Date ngaynhap, Integer soluong, Boolean dahuy, String mancc, String manv, String macn) {
       this.machungtu = machungtu;
       this.ngaylap = ngaylap;
       this.ngaynhap = ngaynhap;
       this.soluong = soluong;
       this.dahuy = dahuy;
       this.mancc = mancc;
       this.manv = manv;
       this.macn = macn;
    }
   
    public String getMachungtu() {
        return this.machungtu;
    }
    
    public void setMachungtu(String machungtu) {
        this.machungtu = machungtu;
    }
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }
    public Date getNgaynhap() {
        return this.ngaynhap;
    }
    
    public void setNgaynhap(Date ngaynhap) {
        this.ngaynhap = ngaynhap;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Boolean getDahuy() {
        return this.dahuy;
    }
    
    public void setDahuy(Boolean dahuy) {
        this.dahuy = dahuy;
    }
    public String getMancc() {
        return this.mancc;
    }
    
    public void setMancc(String mancc) {
        this.mancc = mancc;
    }
    public String getManv() {
        return this.manv;
    }
    
    public void setManv(String manv) {
        this.manv = manv;
    }
    public String getMacn() {
        return this.macn;
    }
    
    public void setMacn(String macn) {
        this.macn = macn;
    }




}


