package pojos;
// Generated May 29, 2017 11:41:03 AM by Hibernate Tools 4.3.1



/**
 * TablesCounter generated by hbm2java
 */
public class TablesCounter  implements java.io.Serializable {


     private String key;
     private Integer phieuxuat;
     private Integer phieunhap;

    public TablesCounter() {
    }

	
    public TablesCounter(String key) {
        this.key = key;
    }
    public TablesCounter(String key, Integer phieuxuat, Integer phieunhap) {
       this.key = key;
       this.phieuxuat = phieuxuat;
       this.phieunhap = phieunhap;
    }
   
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public Integer getPhieuxuat() {
        return this.phieuxuat;
    }
    
    public void setPhieuxuat(Integer phieuxuat) {
        this.phieuxuat = phieuxuat;
    }
    public Integer getPhieunhap() {
        return this.phieunhap;
    }
    
    public void setPhieunhap(Integer phieunhap) {
        this.phieunhap = phieunhap;
    }




}


