package pojos;
// Generated May 30, 2017 5:04:37 PM by Hibernate Tools 4.3.1



/**
 * Counter generated by hbm2java
 */
public class Counter  implements java.io.Serializable {


     private String areaid;
     private Integer indexBo;
     private Integer indexChinhanh;
     private Integer indexChuongtrai;
     private Integer indexKhosua;
     private Integer indexNhacungcap;
     private Integer indexNhanvien;

    public Counter() {
    }

	
    public Counter(String areaid) {
        this.areaid = areaid;
    }
    public Counter(String areaid, Integer indexBo, Integer indexChinhanh, Integer indexChuongtrai, Integer indexKhosua, Integer indexNhacungcap, Integer indexNhanvien) {
       this.areaid = areaid;
       this.indexBo = indexBo;
       this.indexChinhanh = indexChinhanh;
       this.indexChuongtrai = indexChuongtrai;
       this.indexKhosua = indexKhosua;
       this.indexNhacungcap = indexNhacungcap;
       this.indexNhanvien = indexNhanvien;
    }
   
    public String getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }
    public Integer getIndexBo() {
        return this.indexBo;
    }
    
    public void setIndexBo(Integer indexBo) {
        this.indexBo = indexBo;
    }
    public Integer getIndexChinhanh() {
        return this.indexChinhanh;
    }
    
    public void setIndexChinhanh(Integer indexChinhanh) {
        this.indexChinhanh = indexChinhanh;
    }
    public Integer getIndexChuongtrai() {
        return this.indexChuongtrai;
    }
    
    public void setIndexChuongtrai(Integer indexChuongtrai) {
        this.indexChuongtrai = indexChuongtrai;
    }
    public Integer getIndexKhosua() {
        return this.indexKhosua;
    }
    
    public void setIndexKhosua(Integer indexKhosua) {
        this.indexKhosua = indexKhosua;
    }
    public Integer getIndexNhacungcap() {
        return this.indexNhacungcap;
    }
    
    public void setIndexNhacungcap(Integer indexNhacungcap) {
        this.indexNhacungcap = indexNhacungcap;
    }
    public Integer getIndexNhanvien() {
        return this.indexNhanvien;
    }
    
    public void setIndexNhanvien(Integer indexNhanvien) {
        this.indexNhanvien = indexNhanvien;
    }




}


