package pojos;
// Generated May 25, 2017 7:26:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String manhanvien;
     private String hoten;
     private String gioitinh;
     private Date ngaysinh;
     private String sodt;
     private String diachi;
     private String email;
     private String tentaikhoan;
     private String matkhau;
     private String tinhtrang;
     private Boolean daxoa;
     private String machinhanh;
     private String maphanquyen;

    public Nhanvien() {
    }

	
    public Nhanvien(String manhanvien) {
        this.manhanvien = manhanvien;
    }
    public Nhanvien(String manhanvien, String hoten, String gioitinh, Date ngaysinh, String sodt, String diachi, String email, String tentaikhoan, String matkhau, String tinhtrang, Boolean daxoa, String machinhanh, String maphanquyen) {
       this.manhanvien = manhanvien;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.ngaysinh = ngaysinh;
       this.sodt = sodt;
       this.diachi = diachi;
       this.email = email;
       this.tentaikhoan = tentaikhoan;
       this.matkhau = matkhau;
       this.tinhtrang = tinhtrang;
       this.daxoa = daxoa;
       this.machinhanh = machinhanh;
       this.maphanquyen = maphanquyen;
    }
   
    public String getManhanvien() {
        return this.manhanvien;
    }
    
    public void setManhanvien(String manhanvien) {
        this.manhanvien = manhanvien;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public String getSodt() {
        return this.sodt;
    }
    
    public void setSodt(String sodt) {
        this.sodt = sodt;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTentaikhoan() {
        return this.tentaikhoan;
    }
    
    public void setTentaikhoan(String tentaikhoan) {
        this.tentaikhoan = tentaikhoan;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public Boolean getDaxoa() {
        return this.daxoa;
    }
    
    public void setDaxoa(Boolean daxoa) {
        this.daxoa = daxoa;
    }
    public String getMachinhanh() {
        return this.machinhanh;
    }
    
    public void setMachinhanh(String machinhanh) {
        this.machinhanh = machinhanh;
    }
    public String getMaphanquyen() {
        return this.maphanquyen;
    }
    
    public void setMaphanquyen(String maphanquyen) {
        this.maphanquyen = maphanquyen;
    }




}


