package pojos;
// Generated May 29, 2017 11:39:08 AM by Hibernate Tools 4.3.1



/**
 * TablesCounter generated by hbm2java
 */
public class TablesCounter  implements java.io.Serializable {


     private String key;
     private Integer bo;
     private Integer chinhanh;
     private Integer chuongtrai;
     private Integer khosua;
     private Integer nhacungcap;
     private Integer nhanvien;

    public TablesCounter() {
    }

	
    public TablesCounter(String key) {
        this.key = key;
    }
    public TablesCounter(String key, Integer bo, Integer chinhanh, Integer chuongtrai, Integer khosua, Integer nhacungcap, Integer nhanvien) {
       this.key = key;
       this.bo = bo;
       this.chinhanh = chinhanh;
       this.chuongtrai = chuongtrai;
       this.khosua = khosua;
       this.nhacungcap = nhacungcap;
       this.nhanvien = nhanvien;
    }
   
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public Integer getBo() {
        return this.bo;
    }
    
    public void setBo(Integer bo) {
        this.bo = bo;
    }
    public Integer getChinhanh() {
        return this.chinhanh;
    }
    
    public void setChinhanh(Integer chinhanh) {
        this.chinhanh = chinhanh;
    }
    public Integer getChuongtrai() {
        return this.chuongtrai;
    }
    
    public void setChuongtrai(Integer chuongtrai) {
        this.chuongtrai = chuongtrai;
    }
    public Integer getKhosua() {
        return this.khosua;
    }
    
    public void setKhosua(Integer khosua) {
        this.khosua = khosua;
    }
    public Integer getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Integer nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Integer getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Integer nhanvien) {
        this.nhanvien = nhanvien;
    }




}


